version: '3.4'

services:  
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports: 
      - 27017:27017
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
    ports:
      - 8081:8081
    links:
      - mongo
    depends_on: 
      - mongo