POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI1YjMxMDQzNjI4MDk5MWMzN2EyNjgzZDMiLCJpYXQiOjE1Mjk5Mzk2MjJ9.sIcw2WLpE5U6dh1kex5btomRG84W0WXkCBsNeDVuzbg

{
    "author": "Me",
    "title": "title",
    "url": "http://localhost:1234",
    "likes": 1
}